import Head from "next/head";
import Header from "../Layout/Header";
import SectionChoice from "../Layout/SectionChoice";
import SectionSearch from "../Layout/SectionSearch";
import SectionCards from "../Layout/SectionCards";
import Footer from "../Layout/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SectionChoice />
      <SectionSearch />
      <SectionCards />
      <Footer />
    </>
  );
}
